- name: Download Bowtie
  get_url:
    url=http://sourceforge.net/projects/bowtie-bio/files/bowtie/{{version}}/bowtie-{{version}}-linux-x86_64.zip
    dest={{source_dir}}/bowtie-{{version}}-linux-x86_64.zip

- name: Uncompress Bowtie
  unarchive: 
    src={{ source_dir }}/bowtie-{{version}}-linux-x86_64.zip
    dest={{ soft_dir }}
    copy=no
    creates={{ soft_dir}}/bowtie-{{version}}/bowtie-align-s

- file: dest="{{modules_dir}}/bio/bowtie" state=directory mode=0755

- name: Bowtie module definition
  template: 
    src: templates/sw-module.lua.j2 
    dest: "{{ modules_dir }}/bio/bowtie/{{version}}.lua"
    owner: root 
    mode: 644
  with_items:
    - { help_text: 'Bowtie, an ultrafast, memory-efficient short read aligner for short DNA sequences (reads) from next-gen sequencers', dir: 'bowtie-{{version}}', skip_bin: true}


