
- name: Download IGV - you should register here https://www.broadinstitute.org/software/igv/?q=registration and agree with the license terms (LGPL, http://www.opensource.org/licenses/lgpl-2.1.php)
  get_url:
    url=http://data.broadinstitute.org/igv/projects/downloads/IGV_{{version}}.zip
    dest={{source_dir}}/IGV_{{version}}.zip

- stat: path={{source_dir}}/IGV_{{version}}.zip
  register: igvzip

# Check if it has been uncompressed.  The "creates" in the next section should do this, but it
# seems to copy up the tarball anyway
- stat: path={{ soft_dir}}/IGV_{{version}}/igv.sh
  register: igv

- name: Uncompress igv
  unarchive: 
    src={{source_dir}}/IGV_{{version}}.zip
    dest={{ soft_dir }}
    copy=no
    creates={{ soft_dir}}/IGV_{{version}}/igv.sh
  when: not igv.stat.exists and igvzip.stat.exists

- debug: msg="Didn't find IGV_{{version}}.zip - not installing IGV"
  when: not igvzip.stat.exists

- file: dest="{{modules_dir}}/bio/igv" state=directory mode=0755

- name: igv module definition
  template: 
    src: templates/sw-module.lua.j2 
    dest: "{{ modules_dir }}/bio/igv/{{version}}.lua"
    owner: root 
    mode: 0644
  with_items:
    - { help_text: 'IGV genome browser', dir: 'IGV_{{version}}', skip_bin: true }


