# Link any installed jvms into lmod modules
# TODO: this really should be done on a per-host basis since /usr/lib/jvm is per system
# but that will also require a per-system modules directory (which we should also have!)

- name: Find installed jvms
  script: scripts/find-jvms
  register: json_txt

- set_fact: 
    jvms: "{{json_txt.stdout|from_json}}"

#- debug: var=jvms

- file: dest="{{modules_dir}}/core/java" state=directory mode=0755

- name: java module definition
  template:
    src: templates/sw-module.lua.j2
    dest: "{{ modules_dir }}/core/java/{{item.version}}.lua"
    owner: root
    mode: 0644
  with_items: jvms
