
- file: path={{brew_dir}} owner=sw-installer state=directory mode=0755

- name: Clone Linuxbrew
  git: repo=https://github.com/Homebrew/linuxbrew.git
       update=no
       dest={{brew_dir}}
  sudo: yes
  sudo_user: sw-installer

- name: Copy brew2lmod
  copy: src=scripts/brew2lmod.rb dest={{brew_dir}} owner=sw-installer mode=0755

