
- include: brew_package.yml brew_name='parallel' lmod_name='parallel'
- include: brew_package.yml brew_name='homebrew/science/plink' lmod_name='plink'
- include: brew_package.yml brew_name='homebrew/science/fastqc' lmod_name='fastqc'

- include: brew_package.yml brew_name='homebrew/science/aragorn' lmod_name='aragorn'
- include: brew_package.yml brew_name='homebrew/science/prodigal' lmod_name='prodigal'
- include: brew_package.yml brew_name='homebrew/science/infernal' lmod_name='infernal'
- include: brew_package.yml brew_name='homebrew/science/hmmer' lmod_name='hmmer'
- include: brew_package.yml brew_name='homebrew/science/barrnap' lmod_name='barrnap'
- include: brew_package.yml brew_name='homebrew/science/tbl2asn' lmod_name='tbl2asn'
- include: brew_package.yml brew_name='homebrew/science/freec' lmod_name='freec'

#- include: brew_package.yml brew_name='homebrew/science/plink2' lmod_name='plink2'
#- include: brew_package.yml brew_name='homebrew/science/repeatmasker' lmod_name='repeatmasker'
