
- name: Download Picard
  get_url:
    url=https://github.com/broadinstitute/picard/releases/download/{{version}}/picard-tools-{{version}}.zip
    dest={{source_dir}}/picard-tools-{{version}}.zip
    timeout=30
  register: get_url_result
  until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
  retries: 5
  delay: 10

- name: Uncompress Picard
  unarchive: 
    src: "{{ source_dir }}/picard-tools-{{version}}.zip"
    dest: "{{ soft_dir }}"
    copy: no
    creates: "{{ soft_dir }}/picard-tools-{{version}}/picard.jar"

- file: dest="{{ soft_dir }}/picard-tools-{{version}}/bin" state=directory mode=0755

- name: Picard wrapper script
  template:
    src: templates/java-wrapper.sh.j2
    dest: "{{ soft_dir }}/picard-tools-{{version}}/bin/picard"
    owner: root 
    mode: 0755
  with_items:
    - { jar: '{{ soft_dir }}/picard-tools-{{version}}/picard.jar' }

- file: dest="{{modules_dir}}/bio/picard" state=directory mode=0755

- name: Picard module definition
  template: 
    src: templates/sw-module.lua.j2 
    dest: "{{ modules_dir }}/bio/picard/{{version}}.lua"
    owner: root 
    mode: 0644
  with_items:
    - { help_text: 'This module loads the Picard tool suite', dir: 'picard-tools-{{version}}' }


