
- file: dest="{{ soft_dir }}/RNA-SeQC_v{{version}}" state=directory mode=0755

- name: Download RNA-SeQC
  get_url:
    url=http://www.broadinstitute.org/cancer/cga/tools/rnaseqc/RNA-SeQC_v{{version}}.jar
    dest={{ soft_dir }}/RNA-SeQC_v{{version}}/RNA-SeQC_v{{version}}.jar

- name: RNA-SeQC wrapper script
  template:
    src: templates/java-wrapper.sh.j2
    dest: "{{ soft_dir }}/RNA-SeQC_v{{version}}/rna-seqc"
    owner: root 
    mode: 0755
  with_items:
    - { jar: '{{ soft_dir }}/RNA-SeQC_v{{version}}/RNA-SeQC_v{{version}}.jar' }

- file: dest="{{modules_dir}}/bio/RNA-SeQC" state=directory mode=0755

- name: RNA-SeQC module definition
  template: 
    src: templates/sw-module.lua.j2 
    dest: "{{ modules_dir }}/bio/RNA-SeQC/{{version}}.lua"
    owner: root 
    mode: 644
  with_items:
    - { help_text: 'RNA-SeQC is a java program which computes a series of quality control metrics for RNA-seq data', dir: 'RNA-SeQC_v{{version}}', skip_bin: true }


