---

- name: Download bcftools
  get_url:
    url=https://github.com/samtools/bcftools/releases/download/{{version}}/bcftools-{{version}}.tar.bz2
    dest={{source_dir}}/bcftools-{{version}}.tar.bz2

- name: Uncompress bcftools
  unarchive: 
    src: "{{ source_dir }}/bcftools-{{version}}.tar.bz2"
    dest: "{{ source_dir }}"
    copy: no
    creates: "{{ source_dir }}/bcftools-{{version}}/README"

- name: Build and Install bcftools
  shell: cd {{ source_dir }}/bcftools-{{version}}; make install prefix="{{ soft_dir }}/bcftools-{{version}}"
  args:
    creates: "{{ soft_dir }}/bcftools-{{version}}/bin/bcftools"

- file: dest="{{modules_dir}}/bio/bcftools" state=directory mode=0755

- name: bcftools module definition
  template:
    src: sw-module.lua.j2
    dest: "{{ modules_dir }}/bio/bcftools/{{version}}.lua"
    owner: root
    mode: 0644
  with_items:
    - { help_text: 'BCFtools are meant as a faster replacement for most of the perl VCFtools commands', dir: 'bcftools-{{version}}' }

