---

- name: Download bedops
  get_url:
    url=https://github.com/bedops/bedops/releases/download/v{{version}}/bedops_linux_x86_64-v{{version}}.tar.bz2
    dest={{source_dir}}/bedops_linux_x86_64-v{{version}}.tar.bz2

- file: dest="{{soft_dir}}/bedops-{{version}}" state=directory mode=0755

- name: Uncompress bedops
  unarchive: 
    src={{source_dir}}/bedops_linux_x86_64-v{{version}}.tar.bz2
    dest={{ soft_dir }}/bedops-{{version}}
    copy=no
    creates={{ soft_dir }}/bedops-{{version}}/bin/bam2bed

- file: dest="{{modules_dir}}/bio/bedops" state=directory mode=0755

- name: bedops module definition
  template: 
    src: sw-module.lua.j2 
    dest: "{{ modules_dir }}/bio/bedops/{{version}}.lua"
    owner: root 
    mode: 0644
  with_items:
    - { help_text: 'BEDOPS: high-performance genomic feature operations https://bedops.readthedocs.org/', dir: 'bedops-{{version}}'}


