---

# Ensure the unarchive directory exists (the zip file has no version info)
- file: dest="{{ soft_dir }}/IGVTools-{{version}}" state=directory mode=0755

# Check if it has been uncompressed.  The "creates" in the next section should do this, but it
# seems to copy up the tarball anyway
- stat: path={{ soft_dir }}/IGVTools-{{version}}/IGVTools/igvtools
  register: igvtools

- name: Uncompress igvtools
  unarchive: 
    src=tarballs/igvtools_{{version}}.zip
    dest={{ soft_dir }}/IGVTools-{{version}}
    copy=yes
    creates={{ soft_dir }}/IGVTools-{{version}}/IGVTools/igvtools
  when: not igvtools.stat.exists

- file: dest="{{modules_dir}}/bio/igvtools" state=directory mode=0755

- name: igvtools module definition
  template: 
    src: sw-module.lua.j2 
    dest: "{{ modules_dir }}/bio/igvtools/{{version}}.lua"
    owner: root 
    mode: 0644
  with_items:
    - { help_text: 'Tools for use with the IGV browser', dir: 'IGVTools-{{version}}/IGVTools', skip_bin: true }
