---

- name: Download ngsutils
  git: repo=https://github.com/ngsutils/ngsutils
       dest={{soft_dir}}/ngsutils-{{version}}
       version=ngsutils-{{version}}

- name: Install ngsutils
  shell: cd {{ soft_dir }}/ngsutils-{{version}}; make
  args:
    creates: "{{ soft_dir }}/ngsutils-{{version}}/venv/bin/python"

- file: dest="{{modules_dir}}/bio/ngsutils" state=directory mode=0755

- name: ngsutils module definition
  template: 
    src: sw-module.lua.j2 
    dest: "{{ modules_dir }}/bio/ngsutils/{{version}}.lua"
    owner: root 
    mode: 0644
  with_items:
    - help_text: 'NGSUtils is a suite of software tools for working with next-generation sequencing datasets.  Separated in 4 modules: bamutils, bedutils, fastqutils, gtfutils'
      dir: 'ngsutils-{{version}}'
      depend: '"htslib"'           # For tabix
