---

# RNAsik-pipe-version1.1
- name: Git Clone RNAsik-pipe
  git: repo=https://github.com/monashbioinformaticsplatform/RNAsik-pipe.git
       dest={{ soft_dir }}/{{version}}
       version={{version}}
       update=no

- file: dest="{{modules_dir}}/bio/RNAsik-pipe" state=directory mode=0755

- name: RNAsik-pipe module definition
  template: 
    src: sw-module.lua.j2 
    dest: "{{ modules_dir }}/bio/RNAsik-pipe/{{version}}.lua"
    owner: root
    mode: 0644
  with_items:
    - { help_text: 'This module loads Kirill RNAsik-pipe release version {{RNAsik-pipe-version1.1}}',
    dir: '{{version}}', skip_bin: true,
    base: '{{ soft_dir }}/{{version}}/src' }
