---

- name: Download snippy
  git: repo=https://github.com/tseemann/snippy
       dest={{soft_dir}}/snippy-{{version}}
       version=v{{version}}

- file: dest="{{modules_dir}}/bio/snippy" state=directory mode=0755

- name: snippy module definition
  template: 
    src: sw-module.lua.j2 
    dest: "{{ modules_dir }}/bio/snippy/{{version}}.lua"
    owner: "{{ sw_installer }}" 
    mode: 0644
  with_items:
    - { help_text: 'Rapid haploid variant calling and core SNP phylogeny', dir: 'snippy-{{version}}' }


