---

- name: Download STAR
  git: repo=https://github.com/alexdobin/STAR
       dest={{source_dir}}/STAR-{{version}}
       version=STAR_{{version}}

- name: Install STAR
  shell: cd {{ source_dir }}/STAR-{{version}}/bin/Linux_x86_64_static; mkdir -p "{{ soft_dir }}/STAR-{{version}}/bin" && cp STAR STARlong "{{ soft_dir }}/STAR-{{version}}/bin"
  args:
    creates: "{{ soft_dir }}/STAR-{{version}}/bin/STAR"

- file: dest="{{modules_dir}}/bio/STAR" state=directory mode=0755

- name: STAR module definition
  template: 
    src: sw-module.lua.j2 
    dest: "{{ modules_dir }}/bio/STAR/{{version}}.lua"
    owner: "{{ sw_installer }}" 
    mode: 0644
  with_items:
    - { help_text: 'This module loads the STAR aligner', dir: 'STAR-{{version}}' }


