---

- name: Download vcftools
  get_url:
    url=http://downloads.sourceforge.net/project/vcftools/vcftools_{{version}}.tar.gz
    dest={{source_dir}}/vcftools_{{version}}.tar.gz

- name: Uncompress vcftools
  unarchive: 
    src: "{{ source_dir }}/vcftools_{{version}}.tar.gz"
    dest: "{{ source_dir }}"
    copy: no
    creates: "{{ source_dir }}//vcftools_{{version}}/README.txt"

- name: Build and Install vcftools
  shell: cd {{ source_dir }}/vcftools_{{version}}; make install PREFIX="{{ soft_dir }}/vcftools_{{version}}"
  args:
    creates: "{{ soft_dir }}/vcftools_{{version}}/bin/vcftools"

- file: dest="{{modules_dir}}/bio/vcftools" state=directory mode=0755

- name: vcftools module definition
  template:
    src: sw-module.lua.j2
    dest: "{{ modules_dir }}/bio/vcftools/{{version}}.lua"
    owner: "{{ sw_installer }}"
    mode: 0644
  with_items:
    - dir: 'vcftools_{{version}}' 
      perl_path: 'lib/perl5/site_perl'
      help_text: >
        This module loads the vcftools tool suite

