---

- name: Download BBMap
  get_url:
    url=http://sourceforge.net/projects/bbmap/files/BBMap_{{version}}.tar.gz/download
    dest={{source_dir}}/BBMap-{{version}}.tgz

- file: dest="{{ soft_dir }}/BBMap-{{version}}" state=directory mode=0755

- name: Uncompress BBMap
  unarchive: 
    src: "{{ source_dir }}/BBMap-{{version}}.tgz"
    dest: "{{ soft_dir }}/BBMap-{{version}}"
    copy: no
    creates: "{{ soft_dir }}/BBMap-{{version}}/bbmap/bbmap.sh"

# Fix file permissions
- shell: find {{ soft_dir }}/BBMap-{{version}} -type d -exec chmod 0755 {} \; ; find {{ soft_dir }}/BBMap-{{version}} -type f -exec chmod 0644 {} \; ; chmod 0755 {{ soft_dir }}/BBMap-{{version}}/bbmap/*.sh

- file: dest="{{modules_dir}}/bio/BBMap" state=directory mode=0755

- name: BBMap module definition
  template: 
    src: sw-module.lua.j2 
    dest: "{{ modules_dir }}/bio/BBMap/{{version}}.lua"
    owner: "{{ sw_installer }}" 
    mode: 0644
  with_items:
    - help_text: 'BBMap, a short read aligner, as well as various other bioinformatic tools'
      dir: 'BBMap-{{version}}/bbmap'
      skip_bin: true


