---

- file: dest="{{soft_dir}}/homer" state=directory mode=0755

- name: Download Homer
  get_url:
    url=http://homer.salk.edu/homer/configureHomer.pl
    dest={{soft_dir}}/homer/configureHomer.pl

- name: Build Homer
  shell: cd {{ soft_dir }}/homer; perl configureHomer.pl -install
  args:
    creates: "{{ soft_dir }}/homer/bin/homer"

- file: dest="{{modules_dir}}/bio/homer" state=directory mode=0755

- name: Homer module definition
  template: 
    src: sw-module.lua.j2 
    dest: "{{ modules_dir }}/bio/homer/default.lua"
    owner: "{{ sw_installer }}" 
    mode: 0644
  with_items:
    - { help_text: 'Software for motif discovery and next-gen sequencing analysis', dir: 'homer' }


