---

- name: Download BAMStats
  get_url:
    url=http://sourceforge.net/projects/bamstats/files/BAMStats-{{version}}.zip/download
    dest={{source_dir}}/BAMStats-{{version}}.zip

- name: Uncompress BAMStats
  unarchive: 
    src: "{{ source_dir }}/BAMStats-{{version}}.zip"
    dest: "{{ soft_dir }}"
    copy: no
    creates: "{{ soft_dir }}/BAMStats-{{version}}/BAMStats-{{version}}.jar"

- file: dest="{{ soft_dir }}/BAMStats-{{version}}/bin" state=directory mode=0755

- name: BAMStats wrapper script
  template:
    src: templates/java-wrapper.sh.j2
    dest: "{{ soft_dir }}/BAMStats-{{version}}/bin/{{item.bin}}"
    owner: root 
    mode: 0755
  with_items:
    - { bin: 'BAMStats', jar: '{{ soft_dir }}/BAMStats-{{version}}/BAMStats-{{version}}.jar' }
    - { bin: 'BAMStatsGUI', jar: '{{ soft_dir }}/BAMStats-{{version}}/BAMStats-GUI-{{version}}.jar' }

- file: dest="{{modules_dir}}/bio/BAMStats" state=directory mode=0755

- name: BAMStats module definition
  template: 
    src: templates/sw-module.lua.j2 
    dest: "{{ modules_dir }}/bio/BAMStats/{{version}}.lua"
    owner: root 
    mode: 0644
  with_items:
    - { help_text: 'BAMStats: an interactive desktop GUI tool for summarising Next Generation Sequencing alignments', dir: 'BAMStats-{{version}}' }


