---

- name: Adding cran mirror to sources.list
  apt_repository: repo='deb http://cran.ms.unimelb.edu.au/bin/linux/ubuntu trusty/' state=present update_cache=yes

- name: Install R packages
  apt: pkg={{item}} state=present
  with_items:
    - r-cran-ggplot2
    - r-bioc-biobase
    - r-bioc-limma
    - r-bioc-edger
    - r-bioc-cummerbund
    - r-bioc-biomart
    - r-bioc-biovizbase
    - r-bioc-genomicfeatures
    - r-bioc-genomicranges
    - r-bioc-iranges
    - r-bioc-rsamtools
    - r-bioc-shortread
